{
 "title": "Mosquitto Broker",
 "description": "Mosquitto Broker",
 "tags": [ "mosquitto" ],
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rate Messages sent by Broker",
   "type": "graph",
   "description": "The total number of messages of any type sent since the broker started.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mosquitto_messages_sent [1m])"
    }
   ]
  },
  {
   "title": "Uptime mosquitto",
   "type": "stat",
   "description": "The amount of time in seconds the broker has been online.",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mosquitto_uptime" }
   ]
  },
  {
   "title": "Total  Byte received",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mosquitto_bytes_received" }
   ]
  },
  {
   "title": "Client Connected",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mosquitto_clients_connected" }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mosquitto_bytes_sent" }
   ]
  },
  {
   "title": "Total  messages received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mosquitto_messages_received" }
   ]
  },
  {
   "title": "Rate Bytes received by Broker",
   "type": "graph",
   "description": "The total number of Bytes of any type received since the broker started.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mosquitto_bytes_received [1m])"
    }
   ]
  },
  {
   "title": "Rate Bytes sent by Broker",
   "type": "graph",
   "description": "The total number of Bytes of any type sent since the broker started.",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mosquitto_bytes_sent [1m])"
    }
   ]
  },
  {
   "title": "Message received by Broker - 1min",
   "type": "graph",
   "description": "The moving average of the number of all types of MQTT messages received by the broker over different time intervals",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mosquitto_load_messages_received_1min"
    }
   ]
  },
  {
   "title": "Message sent by Broker - 1min",
   "type": "graph",
   "description": "The moving average of the number of all types of MQTT messages sent by the broker over different time intervals",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mosquitto_load_messages_sent_1min"
    }
   ]
  }
 ]
}