version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    labels:
      org.label-schema.group: "monitoring"

  mosquitto-exporter:
    image: alessandrovito/mosquitto-exporter-docker:1.0
    container_name: mosquitto-exporter
    #entrypoint: /run.sh
    environment:
      - MOSQUITTO_USER=${MS_USER:-fairfoot513}
      - MOSQUITTO_PASSWORD=${MS_PASSWORD:-CBPB0ntFBGMo1x2t}
      - MOSQUITTO_HOSTNAME=${MS_HOSTNAME:-mosquitto}
    restart: unless-stopped
    ports:
      - "9180:9180"
    labels:
      org.label-schema.group: "monitoring"

  services:
    prometheus:
      image: prom/prometheus:v2.30.3
      ports:
        - 9000:9090
      volumes:
        - ./prometheus:/etc/prometheus
        - prometheus-data:/prometheus
      command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

