version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    labels:
      org.label-schema.group: "monitoring"

  mosquitto-exporter:
    image: alessandrovito/mosquitto-exporter-docker:1.0
    container_name: mosquitto-exporter
    #entrypoint: /run.sh
    environment:
      - MOSQUITTO_USER=${MS_USER:-fairfoot513}
      - MOSQUITTO_PASSWORD=${MS_PASSWORD:-CBPB0ntFBGMo1x2t}
      - MOSQUITTO_HOSTNAME=${MS_HOSTNAME:-mosquitto}
    restart: unless-stopped
    ports:
      - "9180:9180"
    labels:
      org.label-schema.group: "monitoring"

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    ports:
      - "9090:9090"
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:8.2.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana/
      - ./grafana/provisioning:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"
    labels:
      org.label-schema.group: "monitoring"

