{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Uptime mosquitto",
   "type": "singlestat",
   "description": "The amount of time in seconds the broker has been online.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "mosquitto_uptime" }
   ]
  },
  {
   "title": "Client Connected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mosquitto_clients_connected" }
   ]
  },
  {
   "title": "Client Disconnected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mosquitto_clients_disconnected" }
   ]
  },
  {
   "title": "clients_total_count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mosquitto_clients_total" }
   ]
  },
  {
   "title": "Client Connected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mosquitto_clients_connected" }
   ]
  },
  {
   "title": "Client Disconnected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mosquitto_clients_disconnected" }
   ]
  },
  {
   "title": "Total subscriptions count",
   "type": "singlestat",
   "description": "The total number of subscriptions active on the broker.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mosquitto_subscriptions_count" }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Total  messages received",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mosquitto_messages_received" }
   ]
  },
  {
   "title": "Rate Messages received by Broker",
   "type": "graph",
   "description": "The total number of messages of any type received since the broker started.",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mosquitto_messages_received [1m])"
    }
   ]
  },
  {
   "title": "Total  Byte received",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "mosquitto_bytes_received" }
   ]
  },
  {
   "title": "Rate Bytes received by Broker",
   "type": "graph",
   "description": "The total number of Bytes of any type received since the broker started.",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mosquitto_bytes_received [1m])"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Total Messages Sent",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "mosquitto_messages_sent" }
   ]
  },
  {
   "title": "Rate Messages sent by Broker",
   "type": "graph",
   "description": "The total number of messages of any type sent since the broker started.",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mosquitto_messages_sent [1m])"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 15 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "mosquitto_bytes_sent" }
   ]
  },
  {
   "title": "Rate Bytes sent by Broker",
   "type": "graph",
   "description": "The total number of Bytes of any type sent since the broker started.",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mosquitto_bytes_sent [1m])"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Message received by Broker - 1min",
   "type": "graph",
   "description": "The moving average of the number of all types of MQTT messages received by the broker over different time intervals",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mosquitto_load_messages_received_1min"
    }
   ]
  },
  {
   "title": "Socket Connection  opened by Broker - 1 minute",
   "type": "graph",
   "description": "the number of socket connections in 1 minute",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mosquitto_load_sockets_1min" }
   ]
  },
  {
   "title": "Message sent by Broker - 1min",
   "type": "graph",
   "description": "The moving average of the number of all types of MQTT messages sent by the broker over different time intervals",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mosquitto_load_messages_sent_1min"
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "CONNECT packets received by broker 1 min",
   "type": "graph",
   "description": "The moving average of the number of CONNECT packets received by the broker over different time intervals.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mosquitto_load_connections_1min"
    }
   ]
  },
  {
   "title": "PUBLISH message by Broker (received, dropped, sent)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mosquitto_publish_messages_received [1m])",
     "legendFormat": "received messages"
    },
    {
     "expr": "rate(mosquitto_publish_messages_sent [1m])",
     "legendFormat": "sentmessages"
    },
    {
     "expr": "rate(mosquitto_publish_messages_dropped [1m])",
     "legendFormat": "dropped messages"
    }
   ]
  }
 ]
}